import Header from '@/components/Header';
import Dashboard from '@/components/ui/dashboard/Dashboard';
import { useAuthRedirect } from '@/hooks/useAuthRedirect';
import { getToken, removeToken } from '@/lib/auth';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();
  useAuthRedirect();

  useEffect(() => {
    if (!getToken()) router.push('/login');
  }, []);

  return (
    <>
      <Head>
        <title>CleverSolution Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="bg-neutral-900 min-h-screen py-8 px-16">
        <Header />
        <Dashboard />
      </div>
    </>
  );
}
