import LeftNav from '@/components/ui/edit/LeftNav';
import Typography from '@/components/ui/Typography';
import { useAuthRedirect } from '@/hooks/useAuthRedirect';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function EditSite() {
  const router = useRouter();
  useAuthRedirect();

  return (
    <>
      <Head>
        <title>CleverSolution Admin | Edit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="bg-neutral-900 min-h-screen py-8 px-16">
        <Typography variant="title">Edit</Typography>
        <LeftNav />
      </div>
    </>
  );
}
